### ISSUE TITLE
Why the latest version wraps some parameters passed to component?

### ISSUE THREAD

**Issue by ovvn** [dmapper/derby-header#1]
Suppose we have a view function that returns a function

``` coffeescript
  getFunc: ->
    func = (d) ->
      result = "<strong>Groups:</strong> <span style='color:red'>#{d.value}</span><br/>"
      result
    func
```

Passing the function to the component as follows

``` jade
view(is='test', myFunc="{{getFunc()}}")
```

Within a 'test' component's create method

``` coffeescript
create:
   myFunc = model.get 'myFunc'
   console.log myFunc
```

In derby-header 1.0.x it works as expected, i.e. logs an actual function

``` javascript
function(d) {
  var result;
  result = "<strong>Groups:</strong> <span style='color:red'>" + d.value + "</span><br/>";
  return result;
};
```

But in derby-header 1.2.x I'm getting some weird result

``` json
{
  "template": {
    "expression": {
      "segments": [
        "getGroupsHoverCb"
      ],
      "args": [],
      "meta": {
        "source": "getGroupsHoverCb()"
      },
      "lastSegment": "getGroupsHoverCb",
      "parentSegments": null
    }
  },
  "expression": {
    "segments": [
      "getGroupsHoverCb"
    ],
    "args": [],
    "meta": {
      "source": "getGroupsHoverCb()"
    },
    "lastSegment": "getGroupsHoverCb",
    "parentSegments": null
  }
}
```

Why does it wrap the component's parameter?

**Comment by cray0000** [comment]
That's because derby can't pass complex expressions inside the component -- it can't bind them: http://derbyjs.com/docs/derby-0.6/components/scope#attributes-vs-model-data

It was working before because we've being patching the derby-header with the same patch I've been applying for our fork of derby: https://github.com/dmapper/derby/commit/c0f3e0958a1a21cf073c43e95f0873dd8db3ccbb
which was setting the render value into the component's model if it can't bind it. Default behaviour of derby in this situation is to pass the ParentWrapper object (which is an object used by Derby to hold the templates/expressions in a view). Derby has a built-in function to get the render value of an attribute passed into the component -- `this.getAttribute()`. This function is going to get you the render value of the expression at the time when you call it.

Our previous workaround to this wasn't solving the problem -- it wasn't creating a proper binding. Instead it was just storing the initial render value of the attribute into the component's model. It wasn't updating the expression reactively.

So there are couple of things to note regarding the usage of Model data vs Attributes:
1. A complex expression is anything more then a simple variable or constant:
   
   ``` html
   <!-- 'Simple' exrpession - CAN be binded into the component's model -->
   x="{{ #root._page.foobar }}"
   x="{{ 'hello world' }}"
   <!-- Complex expression - CAN NOT be binded - will be ParentWrapper -->
   x="{{ trim( #root._page.foobar ) }}"
   x="{{ #root._page.num + 10 }}"
   ```
2. If you want to pass in a complex expression, you will be able to get only its rendering value with `this.getAttribute('foobar')`. Meaning that you can't use the component's model to get the value. 
   And since you can't get it from the model, you can't listen for its updates using `model.on` or `model.start` or do anything more complicated then getting the value at some particular time with `this.getAttribute('foobar')` or setting it to a new one with `this.setAttribute()`. 
   The good thing though is that when you execute `this.getAttribute('foobar')` you'll get the current value at the time when you are executing it. Unless ofcourse you've changed the attribute with `this.setAttribute('foobar', 'ping pong')` in which case it's going to stay as `'ping pong'` until you set it to some different value.
3. If you want to listen for changes of the attribute you pass inside the component then this attribute HAS to be a simple expression in order to be properly binded into the component's model. If you want to wrap it into some **view function**, you can currently do so only through one of the workarounds. 
   
   Lets say you have a parent component `Player` and you want to show a `Score` for him by getting an `answer` and processing it with the `power()` function:
   
   ``` html
   <index: tag='player'>
     Player {{name}} answered: {{answer}}. 
     His score is <view is='score' />
   ```
   
   You can do one of these:    
   
   **a)** Create a **reactive function** in the parent component and pass its output into the target component:
   
   ``` js
   Player.prototype.init = function() {
     this.model.start( 'result', 'answer', this.power );
   }
   Player.prototype.power = function(x) { return x*x; };
   ```
   
   ``` html
   <view is='score' result='{{ result }}' />
   ```
   
   **b)** Pass the function itself into the target component as an attribute and create the **reactive function** inside the target component itself:
   
   ``` js
   Player.prototype.power = function(x) { return x*x; };
   ```
   
   ``` html
   <view is='score' calcFn='{{ $controller.power }}' value='{{ answer }}' />
   ```
   
   ``` js
   Score.prototype.init = function(){
     this.model.start( 'result', 'value', this.model.get('calcFn') );
   };
   ```
   
   **c)** In some cases it may make sense to split what you are trying to do into 2 components that communicate with each other: 
       - the **main component** that renders stuff 
       - and a helper component which plays a role of a **data adapter** that prepares data for use in the main component
   Here is how the architecture of this can look like: 
   http://codepen.io/cray0000/pen/VYNLVj?editors=101

**Comment by ovvn** [comment]
Ok, thank you for the explanation
